version: '3.8'
# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-permissions-api:
    build:
      target: development
    image: ffc-sfd-permissions-api-development
    container_name: ffc-sfd-permissions-api-development
    ports:
      - "3008:3008"
      - "9008:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
  
  ffc-sfd-permissions-api-postgres:
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}