services:
  ffc-sfd-permissions-api:
    build:
      context: .
      target: production
    image: ffc-sfd-permissions-api
    container_name: ffc-sfd-permissions-api
    depends_on:
      - ffc-sfd-permissions-api-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-permissions-api-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      POSTGRES_DB: ffc_sfd_permissions_api
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-sfd-permissions-api-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  

  ffc-sfd-permissions-api-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfd_permissions_api
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
