services:
  ffc-sfd-permissions-api:
    build:
      context: .
      target: production
    image: ffc-sfd-permissions-api
    container_name: ffc-sfd-permissions-api
    depends_on:
      - ffc-sfd-permissions-api-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-permissions-api-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  ffc-sfd-permissions-api-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc-sfd-permissions-api
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
