{{- include "adp-helm-library.deployment" (list . "ffc-sfd-permissions-api.deployment") -}}
{{- define "ffc-sfd-permissions-api.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "ffc-sfd-permissions-api.container") }}
{{- end -}}
